### ISSUE TITLE
workflow-handler-proxy log level

### ISSUE THREAD

**Issue by jabstone** [node-ts/bus#105]
Hello. We're using the postgres persistence transport and it's working awesome. The one thing I wish I could change is the log level when saving a workflow. In the[ postgres saveWorkFlowData method](https://github.com/node-ts/bus/blob/66b9f10783f4b940970bbcb4f34f8d0ee69c8074/packages/bus-postgres/src/postgres-persistence.ts#L91) the log level is set to debug and works fine. However, the [workflow-handler-proxy](https://github.com/node-ts/bus/blob/66b9f10783f4b940970bbcb4f34f8d0ee69c8074/packages/bus-workflow/src/workflow/registry/workflow-handler-proxy.ts#L78) that calls it appears to write logs at the info level. Actually, the real issue is the logger.info in the proxy includes the entire payload. We're persisting a lot of data between workflow handlers and this logger.info call is destroying our log files. :) Is this by design or an oversight? Ideally, the logger.info would log the workflow name and id and the logger.debug would log the payload. Is this something you would consider changing? I'm happy to submit a PR if necessary. Thanks for this awesome project. It works great.
 
```
  private async persist (data: TWorkflowData): Promise<void> {
    try {
      await this.persistence.saveWorkflowData(data)
      this.logger.info('Saving workflow data', { data })    //This is killing my poor log files
    } catch (err) {
      this.logger.error('Error persisting workflow data', { err })
      throw err
    }
  }
}
```

**Comment by adenhertog** [comment]
hey @jabstone I think you're right - there shouldn't be any need for this to be logging at `info`. Feel free to raise a PR to downgrade this to trace, or I can get it done over the weekend.

Cheers!

**Comment by jabstone** [comment]
Just submitted a PR. Appreciate the quick reply and help on this issue.

**Comment by adenhertog** [comment]
Thanks @jabstone  - your changes are in @node-ts/bus-workflow 0.6.6

**Comment by jabstone** [comment]
Thank you so much for the quick turnaround. Appreciate it!
