### ISSUE TITLE
Not being able to Publish to SQS/SNS with v1

### ISSUE THREAD

**Issue by maganuk** [node-ts/bus#140]
Hi, 

I just upgraded the packages to v1. The queues, topics and subscriptions are being created correctly and debugger is showing that its publishing a message to sqs with the correct queue and topic name / arns, however no message is getting published to the actual queue. Polling on both the sending and receiving end is showing 0 messages. Any suggestions?

UPDATE: Further investigations reveal, that this is working very, very intermittently. It definitely is not working with the default queue policy, works once every 5 times that too if I specify the queue policy (strange since I'm using the default policy from the GeneratePolicy method). I think there might be an Async issue somewhere. This is working fine with the in-memory transport

Thanks
Vishal

**Comment by maganuk** [comment]
Further investigations reveal, that this is working, very very intermittently. It definitely is not working with the default queue policy, works once in every 5 times if I specify the queue policy (strange since I'm using the default policy from the GeneratePolicy method). I think there might be an Async issue somewhere.

**Comment by adenhertog** [comment]
hi @maganuk I've pushed a fix that should address the incorrect policy. I haven't been able to reproduce the "one in 5" issue you mention, could you provide a bit more info about your setup or possibly a code sample so I can get the same bug?

**Comment by maganuk** [comment]
@adenhertog I dont know what went wrong, but I just changed the queue name and it started working with the new policy. Thanks. Closing this.
