### ISSUE TITLE
Type for resolveTopicArn in SQS needs to be fixed

### ISSUE THREAD

**Issue by maganuk** [node-ts/bus#143]
The current type for the options in SQS is incorrect after the update. It expects the function to take in only the topic name. It should be (awsAccountId: string, awsRegion: string, topicName: string) and not just (topicName: string)

**Comment by adenhertog** [comment]
thanks @maganuk really appreciate the report 🙏

**Comment by maganuk** [comment]
@adenhertog thanks for building this wonderful library.
