### ISSUE TITLE
Vulnerability in url-parse - dependency of amqplib

### ISSUE THREAD

**Issue by bdefnall** [node-ts/bus#171]
We are on @node-ts/bus-rabbitmq 0.6.5 which has a dependency on a vulnerable version of url-parse

There is a current open PR here: [https://github.com/node-ts/bus/pull/164](https://github.com/node-ts/bus/pull/164) to resolve this issue.  

Can you please review that pull request? Is it possible to merge that into an 0.6x branch of bus-rabbitmq or would it have breaking changes?

**Comment by adenhertog** [comment]
hey @bdefnall, this has been manually applied and is available in `@node-ts/bus-rabbitmq@0.6.12`
