### ISSUE TITLE
Open to update `bus-sqs` to aws-sdk v3?

### ISSUE THREAD

**Issue by shellscape** [node-ts/bus#198]
Hey there. First, thanks for the packages here. They've been very useful.

Was wondering if you'd be open to a contribution that updates the `bus-sqs` package to use aws-sdk v3. One of the main advantages there is better tree shaking for bundles and the automatic discovery of AWS accountId and region. We're currently using this with a fargate service and there are a number of hoops we have to jump through between local and deployed environments to provide the aws info to `bus-sqs`.

**Comment by adenhertog** [comment]
This was upgraded in https://github.com/node-ts/bus/pull/215
