### ISSUE TITLE
How to set up on different machines?

### ISSUE THREAD

**Issue by haayman-imagem** [node-ts/bus#65]
I'm running a distributed setup with 2 different codebases. machine 1 creates orders and machine 2 handles them. Machine 2 has some handlers/workflows/messages that machine 1 doesn't know about.

What just happened: machine 2 tried to add some messages to the bus, but machine 1 took those messages off the queue complaining that it didn't know how to handle it.

How do I make sure machine 2's messages are kept apart? Is there a way to define 2 seperate messageQueus for RabbitMQ?

**Comment by adenhertog** [comment]
Hey, do you have a repo that demonstrates the issue?

**Comment by haayman-imagem** [comment]
Hi, 

I think I just found the answer: using a different queueName on both machines does the trick. Both queues automatically bind to exchanges they can handle. Works great.
Thanks for the quick reply

**Comment by adenhertog** [comment]
Great, glad to hear
